### ISSUE TITLE
tracker_store can be added to endpoints.yml

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa_core#1035]
**Rasa Core version**:0.11.3

**Python version**: 3.6

**Operating system** (windows, osx, ...): linux

**Issue**:

I think it would be interesting if we can configure the tracker_store info in the endpoints.yml file

```
tracker_store:
 type: redis
 url: abc.com
 timeout: 30000ms
```
