### ISSUE TITLE
HTTP API endpoint to export trained core+nlu models

### ISSUE THREAD

**Issue by nielsrolf** [RasaHQ/rasa_core#1045]
**Rasa Core version**:
rasa-core==0.11.5
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
os x 10.13.1
**Issue**:
I would like to use the rasa HTTP API to train models and then export them from there, or send trained models (core + nlu) to the HTTP API. In the docs I could only find how to import core models, but not nlu models. If this is not a feature already / in progress, I would like to start a PR for that.

**Comment by akelad** [comment]
Thanks for creating this issue, @tmbo  will get back to you about it soon.

**Comment by nielsrolf** [comment]
That makes sense, then I would add POST /model endpoints to the core and the nlu server, right? And I would add that core can take a nlu_model path from endpoints.yml like this:

```
model:
  url: http://my-server.com/models/default_core@latest
nlu:
  url: http://my-nlu-server.com
  project: project from which to take the interpreter
  model: which model to use, optional
```

The exact endpoints would be:
**nlu**:
POST /models/<project> : Save a zipped core model
GET /models/<project>: get a list of model names / ids
GET /models/<project>/<model>: export a zipped model

**core**:
POST /models: Save a zipped model
GET /models: get a list of model ids
GET /models/<id>: export a zipped model

What do you think? Also, should I open an issue in rasa_nlu and link to this one, or is one here sufficient?
