### ISSUE TITLE
Resolve environment variables in endpoints.yml

### ISSUE THREAD

**Issue by souvikg10** [RasaHQ/rasa_core#1083]
**Rasa Core version**:0.11.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): linux

**Issue**:
In my endpoints.yml
```
nlu:
  url: ${NLU_URL}
  params:
    - model_name: ${NLU_MODEL}
    - project_name: ${AGENT}
nlg:
  url: ${NLG_URL}
```
I have environment values. I have also tried directly putting the URL, model name and project name. 
NLG started working but not the NLU, is there something wrong with the params?

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by tmbo** [comment]
@souvikg10 which script is it you are passing that into? 

concerning nlu: there is no `params:` - for the moment model_name and project_name need to passed in using the cli flags: `--nlu project_name/model_name`

not sure env's are resolved automatically

**Comment by tmbo** [comment]
I like the idea of using env's in the yml, might make sense to add this: https://stackoverflow.com/a/52412796/1906073

**Comment by souvikg10** [comment]
@tmbo my NLU is running on a different server

my yaml is looking like this for now
```
nlu:
  url: http://localhost:5000?project_name=project_name&model_name=model_name
nlg:
  url: http://localhost:5056/nlg
action_endpoint:
  url: "http://localhost:5055/webhook"
```
without the env variables 
will this work?
