### ISSUE TITLE
Found unknown intent 'None' on line 3

### ISSUE THREAD

**Issue by Jordanbarker** [RasaHQ/rasa_core#1231]
**Rasa Core version**: 0.11.12

**Python version**:  3.6.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I am running rasa_core.evaluate and getting these errors:

WARNING:rasa_core.training.dsl:Found unknown intent ‘None’ on line 3. Please, make sure that all intents are listed in your domain yaml.
WARNING:rasa_core.training.dsl:Found unknown intent ‘None’ on line 11. Please, make sure that all intents are listed in your domain yaml.
WARNING:rasa_core.training.dsl:Found unknown intent ‘None’ on line 15. Please, make sure that all intents are listed in your domain yaml.
WARNING:rasa_core.training.dsl:Found unknown intent ‘None’ on line 19. Please, make sure that all intents are listed in your domain yaml.

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greeting
  - gibberish
  - affirm
  - deny
  - thankyou

slots:
  dir:
    type: text

entities:
  - dir

actions:
  - utter_greet
  - utter_confused
  - utter_your_welcome
  - utter_sorry
  - utter_great

templates:
  utter_greet:
    - "How can I help?"
    - "Hows it going?"
    - "Whats new?"
    - "Hiya"
    - "Hey buddy"
    - "Lets get to work (⌐■_■)"
    - "Hello •ᴗ•"
  utter_confused:
    - "The heck did you just say to me?"
    - "No comprende"
    - "Say what now?"
    - "Can you try that again"
    - "Huh?"
    - "???"
    - "wat"
    - "I'm not picking up what you're putting down cheif"
    - "(☉_☉)"
  utter_your_welcome:
    - "No problem"
    - "No problemo cheif"
    - "Anytime boss"
    - "Happy to help"
  utter_sorry:
    - "oops"
  utter_great:
    - "going forward"
```

stories.md:
```stories
## Greet
* greeting
	- utter_greet

## Gibberish
* gibberish
    - utter_confused

## Thank
* thankyou
    - utter_your_welcome

## Deny
* deny
    - utter_sorry

## Affirm
* affirm
    - utter_great
```
failed_stories.md:
```failed_stories
## Greet
* None
    - utter_greet   <!-- predicted: utter_confused -->


## Deny
* None
    - utter_sorry   <!-- predicted: utter_confused -->


## Thank
* None
    - utter_your_welcome   <!-- predicted: utter_confused -->


## Affirm
* None
    - utter_great   <!-- predicted: utter_confused -->
```
