### ISSUE TITLE
Variables not sustituted if one of the slots don't exist

### ISSUE THREAD

**Issue by Lucioric2000** [RasaHQ/rasa_core#1485]
**Rasa Core version**:0.12.1

**Python version**: Python 3.6.7 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):CentOS 7

**Issue**: When using variables in templates, if one of the slots does not exist, none of the variables are sustituted.

**Content of domain file** (if used & relevant):
(extract)
```yaml
---
actions:
- utter_blah
- well_utter_blah
config:
  store_entities_as_slots: true
entities:
- var1
- var2
forms:
- formaction1
intents:
- inform
slots:
  var1:
    auto_fill: true
    type: rasa_core.slots.UnfeaturizedSlot
  var2:
    auto_fill: true
    type: rasa_core.slots.UnfeaturizedSlot
  else:
    auto_fill: true
    type: rasa_core.slots.UnfeaturizedSlot

templates:
- utter_blah: "Hello {var1}, {var2}, {absentvar}."
- well_utter_blah= "Hello {var1}, {var2}"
```
for example if var1=='one' and var2=='two', the template well_utter_blah gives the text "Hello one, two", but the template utter_blah gives the text "Hello {var1}, {var2}, {absentvar}.".
