### ISSUE TITLE
Multiple channels per channel type 

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa_core#1625]
Currently it's not possible to serve multiple channels of the same type, e.g. it is not possible to provide two Slack credentials and thereby supply to Slack channels.

Ideally something like this should be possible:
```yaml
slack:
  slack_token: "1234"
  slack_channel: "@my_channel"
slack:
  slack_token: "5678"
  slack_channel: "@another_channel"
```
