### ISSUE TITLE
ModuleNotFoundError: No module named 'actions.actions' when trying to run an action server in a docker container

### ISSUE THREAD

**Issue by leonore** [RasaHQ/rasa_core#1642]
**Rasa Core version**:  0.12.4

**Python version**: 3.6.4

**Operating system** (windows, osx, ...): macOS 10.14.2

**Issue**: Hi, I'm trying to create a docker image that runs the rasa-core action server.
My docker-compose.yml:
```
version: '3'

services:
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./chat-interface:/app/actions
    ports:
      - "5055:5055"
```
Running `docker-compose up` does get the action server up and running:
```INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)```
But I get the following error beforehand:

```
action_server_1  | INFO:__main__:Starting action endpoint server...
action_server_1  | ERROR:rasa_core_sdk.executor:Failed to register package 'actions.actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 144, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
action_server_1  |     package = importlib.import_module(package)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
action_server_1  | ModuleNotFoundError: No module named 'actions.actions'
action_server_1  | INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```
I couldn't figure out what was going wrong so I followed this: https://github.com/RasaHQ/rasa_core/issues/1459#issuecomment-447323161 in another directory, which worked fine 

I tried copying the file structure for that example in my own directory as well but I always get the error 'No module named 'actions.actions''
Am I using the wrong syntax in my yml file? 

Here is my (simplified) directory structure:
```
.
├── chat-interface
│   ├── actions.py
│   ├── agent.py
│   ├── domain.yml
│   ├── endpoints.yml
│   ├── helpers.py
│   ├── main.py
│   ├── nlu-config.yml
│   └── trainer.py
├── LICENSE
├── README.md
├── docker-compose.yml
└── requirements.txt
```

Thanks for any help

**Comment by akelad** [comment]
Thanks for raising this issue, @imLew  will get back to you about it soon.

**Comment by akelad** [comment]
Actually, @wochinge can you take a look instead please

**Comment by wochinge** [comment]
Could you create a directory `actions` in `chat-interface`, put an empty file `__init__.py` in `chat-interface/actions` and restart the docker container?

Second option would be to put an empty file `__init__.py` in `chat-interface` and have a docker-compose file like

```yml
services:
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./chat-interface:/app/actions
    ports:
      - "5055:5055"
    command:
      - start
      - --actions
      - actions
```

Did this help you?

**Comment by leonore** [comment]
Hi, thanks for helping with this - I don't get the error message with this anymore, just: 
```
action_server_1  | INFO:__main__:Starting action endpoint server...
action_server_1  | INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```
but now I can see my actions aren't actually getting registered, which they do when I run `python -m rasa_core_sdk.endpoint --actions actions` in my terminal instead of within the docker container:

```
INFO:__main__:Starting action endpoint server...
INFO:rasa_core_sdk.executor:Registered function for 'action_get_fee'.
INFO:rasa_core_sdk.executor:Registered function for 'action_get_description'.
INFO:__main__:Action endpoint is up and running. on ('0.0.0.0', 5055)
```
So I don't think it's actually finding my actions file anymore.
For clarification purposes, does:
```
volumes:
      - ./chat-interface:/app/actions
```
copy my chat-interface directory in the /app/actions directory of the rasa_core_sdk image?

**Comment by wochinge** [comment]
> does [...] copy my chat-interface directory in the /app/actions directory of the rasa_core_sdk image?
Kind of yes. It mounts the directory in the container. 

In which directory are you running `rasa_core_sdk.endpoint --actions actions`?

I think I did a mistake in my previous comment, please try with:

```yaml
services:
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./chat-interface:/app/actions
    ports:
      - "5055:5055"
```
