### ISSUE TITLE
ERROR:rasa_core.processor:Encountered an exception while running custom action 

### ISSUE THREAD

**Issue by Arghya999** [RasaHQ/rasa_core#1656]
**Rasa Core version**:0.12.3

**Python version**: Python 3.6.8 

**Operating system** (windows, osx, ...):Ubuntu 16.04

**Issue**:ERROR:rasa_core.processor:Encountered an exception while running action' Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

I have a file named bot.py which performs  the nlu,core training logic and starts the bot.
I have kept my custom actions in file called actions.py.
Endpoint is defined in endpoints.yml as 
action_endpoint: 
      url: “http://action:5055/webhook”

I start with    "python -m rasa_core_sdk.endpoint --actions actions"   to run the action server  and then

 "python bot.py --endpoints endpoints.yml" 

to start the bot.
nlu and core training happens smoothly and the bot starts.
The bot is able to run normal utterances but when  it comes to custom actions it throws   

ERROR:rasa_core.processor:Encountered an exception while running action 'action_get_shop_location'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

path of the story :-(though i feel the error is independent of the path) 
## Generated Story -2406084420360357801
* greet{"PERSON": "Arghya"}
    - slot{"PERSON": "Arghya"}
    - utter_greet
* Service_Center_OR_Factory{"workshop_location": "workshop"}
    - slot{"workshop_location": "workshop"}
    - utter_city_name
* city_name{"customer_location": "Delhi"}
    - slot{"customer_location": "Delhi"}
    - action_save_city_name
    - utter_confirm
* mood_affirm
    - action_get_shop_location
    - utter_did_that_help
* mood_affirm
    - utter_mood_affirm
* mood_deny
    - utter_goodbye
    - action_restart

custom code :- (actions.py)

from __future__ import absolute_import
from __future__ import division
from __future__ import unicode_literals

from rasa_core.domain import Domain
from rasa_core.trackers import EventVerbosity

import logging
logger = logging.getLogger(__name__)

import requests
import json

from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet
from rasa_core_sdk.events import UserUtteranceReverted
from rasa_core_sdk.events import AllSlotsReset
from rasa_core_sdk.events import Restarted

class SaveCityName(Action):
    def name(self):
        return 'action_save_city_name'

    def run(self, dispatcher, tracker, domain):
        orig = next(tracker.get_latest_entity_values("customer_location"), None)
        if not orig:
            dispatcher.utter_message("Please enter a valid city name")
            return [UserUtteranceReverted()]
        return [SlotSet('customer_location',orig)]
    
class SaveModelName(Action):
    def name(self):
        return 'action_save_model_name'
        
    def run(self, dispatcher, tracker, domain):
        inp = next(tracker.get_latest_entity_values("model"), None)
        if not inp:
            dispatcher.utter_message("Please enter a valid model")
            return [UserUtteranceReverted()]
        return [SlotSet('model',inp)]
    
class ActionSlotReset(Action):
    def name(self): 
        return 'action_slot_reset'
    def run(self, dispatcher, tracker, domain): 
        return[AllSlotsReset()]
    
class getServiceCentreLocation(Action):
    def name(self):
        return 'action_get_service_centre_location'
    def run(self, dispatcher, tracker, domain):
        print("Checking Location...")
        return "Checking Description..."

class getShopLocation(Action):
    def name(self):
        return 'action_get_shop_location'
    def run(self, dispatcher, tracker, domain):
        print("Checking Location...")
        return "Checking Location..."
    
    
class getModelPrice(Action):
    def name(self):
        return 'action_get_model_price'
    def run(self, dispatcher, tracker, domain):
        print("Checking Price...")
        return "Checking Price..."
    
class getModelConfig(Action):
    def name(self):
        return 'action_get_model_config'
    def run(self, dispatcher, tracker, domain):
        print("Checking Price...")
        return "Checking Price..."  

   

**Content of domain file** (if used & relevant):
```yaml
%YAML 1.1
---
actions:
- utter_CEO_info
- utter_Customer_enquiry_model
- utter_happy
- action_get_model_config
- action_save_city_name
- utter_Service_Center_OR_Factory
- utter_Oppo_shop_location
- action_slot_reset
- utter_CustomerCare_info
- utter_Oppo_product_comparison
- utter_greet
- utter_about_OPPO
- utter_goodbye
- utter_brand_info
- utter_unclear
- utter_Official_Website
- utter_more_info
- utter_model_name_lookout
- utter_check_another_one
- action_get_service_centre_location
- utter_did_that_help
- utter_mood_affirm
- action_save_model_name
- utter_OPPO_Phones_Price
- utter_city_name
- utter_mood_deny
- action_get_shop_location
- utter_provide_founder
- utter_confirm
- utter_thanks
- utter_deny
- action_restart
- action_get_model_price
entities:
- model
- PERSON
- information
- shop_location
- customer_location
- web_address
- workshop_location
- feature
intents:
- mood_affirm
- greet
- Service_Center_OR_Factory
- city_name
- goodbye
- provide_founder
- about_OPPO
- brand_info
- CustomerCare_info
- Oppo_store_location
- CEO_info
- Official_Website
- OPPO_Phones_Price
- Customer_enquiry_model
- Oppo_product_comparison
- model_name_lookout
- mood_deny
slots:
  PERSON:
    type: text
  customer_location:
    type: text
  model:
    type: text
  shop_location:
    type: text
  workshop_location:
    type: text
templates:
  utter_CEO_info:
  - text: CEO of Oppo is Chen Mingyong.Started his position from 2/11/2017.
  utter_CustomerCare_info:
  - text: Oppo's customer care number is 1800 103 2777
  utter_Official_Website:
  - text: 'Official website is: www.oppo.in'
  utter_Oppo_product_comparison:
  - text: 'Decision is yours:Here is the feature list of {model} and {model}:'
  utter_about_OPPO:
  - text: Oppo Electronics Corporation, commonly referred to as Oppo, is a Chinese
      consumer electronics and mobile communication company, known for its smartphones,
      Blu-ray players and other electronic devices. A leading manufacturer of smartphones,
      Oppo was the top smartphone brand in China in 2016 and was ranked No. 8 worldwide
  utter_brand_info:
  - text: I work for Oppo Mobile
  utter_check_another_one:
  - text: Do you want to make another inquiry?
  utter_city_name:
  - text: Which city are you from?
  - text: Which city are you from?
  - text: Name of the city please?
  utter_confirm:
  - text: 'I will be making inquiry for customer_location: {customer_location}. Is
      that correct?'
  utter_deny:
  - text: That's a shame. Let me know if you change your mind.
  utter_did_that_help:
  - text: Did that help you?
  utter_goodbye:
  - text: Bye and take care!
  - text: Bye
  utter_greet:
  - text: Hey!This is Ollie,your assistant.How may I help you?
  - text: Hi!I am here to help.Shoot!
  - text: Hi,how can I help you?
  utter_happy:
  - text: Great carry on!
  utter_mood_affirm:
  - text: Glad that i was useful.Next Question if any?
  utter_mood_deny:
  - text: Try again!
  utter_more_info:
  - text: Please provide more details so that i can understand your query
  utter_provide_founder:
  - text: Oppo's founder is Chen Mingyong.
  utter_thanks:
  - text: You are very welcome.
  - text: Glad I could help!
  utter_unclear:
  - text: I am not sure what you are aiming for.

```
