### ISSUE TITLE
No documentation on how to specify policies in a config file

### ISSUE THREAD

**Issue by rjurney** [RasaHQ/rasa_core#1674]
**Rasa Core version**: 0.13.1

**Python version**: 3.6.6

**Operating system** (windows, osx, ...): OS X 10.14.2

**Issue**: There is no documentation on how to provide policies via a configuration file or how to feed this file to an Agent.

I can't figure a way to achieve this code with a configuration file:

```
agent = Agent('chat_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
```
When I run this I get:
```
Exception: Passing policy configuration parameters to `agent.train(...)` is not supported anymore.
```
When I add a line to my chat domain, it has no effect. What is the correct thing here? I will add it to the docs if only someone will tell me. A google search hits nothing and fifteen minutes with the code yields nothing either.

**Content of domain file** (if used & relevant):
```yaml
intents:
    - order_pizza
    - greet

entities:
    - size
    - toppings

slots:
    size:
         type: text
    toppings:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_get_pizza_size:
        - 'What pizza size?'
    utter_get_pizza_toppings:
        - 'What toppings would you like on your pizza?'
actions:
    - utter_greet
    - utter_get_pizza_size
    - utter_get_pizza_toppings
    - actions.ActionOrderPizza

policies:
    - 'KerasPolicy'
    - 'MemoizationPolicy'
```
