### ISSUE TITLE
ERROR:rasa_core.training.interactive:An exception occurred while recording messages.

### ISSUE THREAD

**Issue by Swarnalathaa** [RasaHQ/rasa_core#1737]
**Rasa Core version**: 
rasa-nlu ==0.14.1
rasa-coe == 0.13.0
rasa-core-sdk==0.12.1
**Python version**: 3.6.8(64bit)

**Operating system** (windows, osx, ...):windows

**Issue**:
I try to train the model online but everytime i get the following error

Chat History

 #    Bot                                                                       You
───────────────────────────────────────────────────────────────────────────────────────────
 1    action_listen
───────────────────────────────────────────────────────────────────────────────────────────
 2                                                                                     hey
                                                                        intent: greet 0.72
───────────────────────────────────────────────────────────────────────────────────────────
 3    utter_greet 1.00
      Hello! How can I help?
      utter_ask_category
      can you choose the category you are interested in?
      Buttons:
      1: Tag
      (/inform{"category":"Tag"})
      2: Market (inform{"category":"Market"})
      action_listen
───────────────────────────────────────────────────────────────────────────────────────────
 4                                                            /inform{"category":"Market"}
                                                                       intent: inform 1.00
───────────────────────────────────────────────────────────────────────────────────────────
 5    slot{"category": "Market"}

Current slots:
        category: Market, name: None

------
? What is the next action of the bot?  0.08 action_listen
Thanks! The bot will now run action_listen.

ERROR:rasa_core.training.interactive:An exception occurred while recording messages.
Traceback (most recent call last):
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\interactive.py", line 1216, in record_messages
    finetune, sender_ids, plot_file)
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\interactive.py", line 824, in _predict_till_next_listen
    _plot_trackers(sender_ids, plot_file, endpoint)
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\interactive.py", line 1151, in _plot_trackers
    max_history=2)
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 448, in visualize_neighborhood
    _merge_equivalent_nodes(graph, max_history)
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 200, in _merge_equivalent_nodes
    _nodes_are_equivalent(graph, i, j, max_history)):
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 145, in _nodes_are_equivalent
    _fingerprint_node(graph, node_b, max_history)))
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 111, in _fingerprint_node
    for continuation in continuations}
  File "C:\Users\swarnalathaa\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\training\visualization.py", line 111, in <setcomp>
    for continuation in continuations}
TypeError: sequence item 1: expected str instance, dict found

**Content of domain file** (if used & relevant):
```yaml
slots:
  category:
    type: text
  name:
    type: text

intents:
 - greet
 - goodbye
 - inform


entities:
  - category
  - name

templates: 
  utter_ask_category: 
    - 
      buttons: 
        - 
          payload: "/inform{\"category\":\"Tag\"}"
          title: Tag
        - 
          payload: "inform{\"category\":\"Market\"}"
          title: Market
      text: "can you choose the category you are interested in?"

  utter_dont_understand: 
    - "Sorry, I dont understand what you are asking for :("
  utter_goodbye: 
    - "Talk to you later."
    - "Bye bye :("
  utter_greet: 
    - "Hello! How can I help?"



actions:
 - utter_greet
 - utter_goodbye
 - utter_ask_category
 - utter_dont_understand
 - action_news
```
**Content of train_interactive.py file** 

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging

from rasa_core.agent import Agent
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_core.train import interactive
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)

def run_news_online(interpreter,
                          domain_file="news_domain.yml",
                          training_data_file='data/stories.md'):
    action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(max_history=2), KerasPolicy(max_history=3, epochs=3, batch_size=50)],
                  interpreter=interpreter,action_endpoint = action_endpoint)				  
    data = agent.load_data(training_data_file)
    agent.train(data)
    interactive.run_interactive_learning(agent, training_data_file)
    return agent

if __name__ == '__main__':
    logging.basicConfig(level="INFO")
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/newsnlu')
    run_news_online(nlu_interpreter)
