### ISSUE TITLE
 train-core: "python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300"  It gives "ImportError: cannot import name Deque".

### ISSUE THREAD

**Issue by aminoacide** [RasaHQ/rasa_core#179]
**Rasa Core version**: 0.8.0a4 | 0.8.0a4-py2.7.egg

**Python version**: 2.7.14 :: Anaconda custom (64-bit)

**Operating system** (windows, osx, ...): ubuntu 16.04

**Issue**: train-core
running command: sudo python -m rasa_core.train -s data/stories.md -d domain.yml -o models/dialogue --epochs 300
When I train-core using "sudo" it gives following error:-
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/rasa_core/train.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/agent.py", line 17, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/policies/__init__.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/policies/policy.py", line 19, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/training/__init__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/training/dsl.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/rasa_core/training/structures.py", line 13, in <module>
ImportError: cannot import name Deque

And when I train-core without using "sudo" it gives following error:-

/home/username/anaconda2/bin/python: No module named rasa_core

**Content of domain file**:
```
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://cdn77.eatliver.com/wp-content/uploads/2017/10/trump-frog.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

actions:
  - utter_greet
  - utter_cheer_up
  - utter_did_that_help
  - utter_happy
  - utter_goodbye


```
thanks adv :)
