### ISSUE TITLE
infer actions

### ISSUE THREAD

**Issue by tycho01** [RasaHQ/rasa_core#183]
The `domain.yml` format as described in the [docs](http://core.rasa.ai/tutorial_basics.html) features some redundancy.

Specifically, the `actions` list appears to be remixing info from the `templates` object, only restating its key names, while Rasa could perceivably just pull this info from `templates` instead. 

I was wondering, was there any specific reason for this? It would seem nice to get rid of this duplication and keep the info in one place, as it would facilitate editing in the event a user renames an action and forgets to update it in both.

(Technically, I suppose a similar argument could be made for the `intents` list, which is arguably just summarizing the intents defined through Rasa NLU.)

Current:

```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://cdn77.eatliver.com/wp-content/uploads/2017/10/trump-frog.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

actions:
  - utter_greet
  - utter_cheer_up
  - utter_did_that_help
  - utter_happy
  - utter_goodbye
```

Proposed:

```yaml
templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://cdn77.eatliver.com/wp-content/uploads/2017/10/trump-frog.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```

That said, congrats on the achievements so far, keep up the good work!
