### ISSUE TITLE
ValueError: action does not correspond to a template/action

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa_core#1850]
HI there I have been triying to make this work and checked multiple times if there are any issues regarding typo but no, I have attached the contents of all the files that i am using, and all of them are in the same directory. Please help

**Rasa Core version**: 0.10.4

**Python version**:  3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
ValueError: Action 'actions.ActionShowMeeting' doesn't correspond to a template / action. Module doesn't contain a class with this name. Remember to prefix actions that should utter a template with `utter_`. Error: module 'actions' has no attribute 'ActionShowMeeting'

**Content of actions.py file** :
```
from rasa_core.actions import Action

class ActionScheduleMeeting(Action):
    def name(self):
        return 'action_schedule_meeting'
    def run(self):
        print('scheduling meeting is completed! ')
        pass

```

**Content of domain file** (if used & relevant):
```yaml
intents:
    - schedule_meeting
    - search_for_meeting
    - greet

entities:
    - meeting
    - time

slots:
    size:
         type: text
    toppings:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
    utter_ask_meeting_day:
        - 'What time would you like me to schedule your meeting?'
    utter_ask_meeting_time:
        - 'What time would you like me to schedule your meeting?'
    utter_get_meeting_time_place:
        - 'here are your meetings for today'
actions:
    - utter_greet
    - utter_ask_meeting_time
    - utter_ask_meeting_day
    - utter_get_meeting_time_place
    - actions.ActionScheduleMeeting
    - actions.ActionShowMeeting

```

**Content of stories file** :
```
## story 01
*greet
    - utter_greet
*schedule_meeting
    - utter_ask_meeting_time
*schedule_meeting
    - action_schedule_meeting
*search_for_meeting
    - utter_get_meeting_time_place
```
