### ISSUE TITLE
Error while training rasa_core 

### ISSUE THREAD

**Issue by mirzahash** [RasaHQ/rasa_core#1868]
**Rasa Core version**: 0.13.3

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): ubuntu

**Issue**: Unable to train rasa-core model

make train-core
python -m rasa_core.train -d domain.yml -s data/stories.md -o models/current/dialogue -c policies.yml
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/train.py", line 6, in <module>
    from rasa_core import config, cli
  File "/usr/local/lib/python2.7/dist-packages/rasa_core/config.py", line 12
    def load(config_file: Optional[Text]) -> List['Policy']:
                        ^
SyntaxError: invalid syntax
Makefile:31: recipe for target 'train-core' failed
make: *** [train-core] Error 1

**Content of domain file** (if used & relevant):
domain.yml file - 
```
intents:
- greet
- goodbye
- thanks
- deny
- joke
- name


entities:
- name


slots:
  name:
    type: text


actions:
- utter_name
- utter_thanks
- utter_greet
- utter_goodbye
- action_joke


templates:
  utter_name:
  - text: "Hey there! Tell me your name."

  utter_greet:
  - text: "Nice to you meet you {name}. How can I help?"

  utter_goodbye:
  - text: "Talk to you later!"

  utter_thanks:
  - text: "My pleasure."
```
