### ISSUE TITLE
Training my model won't give me a good dialog

### ISSUE THREAD

**Issue by Frackup** [RasaHQ/rasa_core#255]
**Rasa Core version** : 0.8.3

**Used backend / pipeline** : spacy_sklearn

**Operating system** : Ubuntu 16.04

**Issue:** Dialog training does not seem to work properly.

Hi all,

First of all, I try to implement a chatbot using Rasa with the french version provided by Spacy, so I will just start by showing here my config file and check with you if it's correctly set up.

Content of configuration file :

```
{
  "pipeline": [
    "nlp_spacy",
    "tokenizer_spacy",
    "intent_entity_featurizer_regex",
    "intent_featurizer_spacy",
    "intent_classifier_sklearn",
    "ner_crf",
    "ner_synonyms"
  ],
  "path" : "./models/nlu",
  "data" : "./data/train_file.json",
  "language" : "fr",
  "response_logs": "logs",
  "log_level": "INFO",
  "spacy_model_name": null
}
```

I completed my domain file with all my intents, entities, slots, actions and templates. Don't think it's interesting to show it, I guess I have correctly created and filled it.

Then I come to the main point, my story.md file. I created one, based on the given examples (eg : restaurant bot) and I put some different dialog within it (I show just a part of it):

```
## Dialogue_bonjour
* bonjour
  - utter_bonjour

## Dialogue_virement_initial
* bonjour
  - utter_bonjour
* realiserVirement
  - utter_demanderMontant
* realiserVirement{"montant": "500"}
  - slot{"montant": "500"}
  - utter_merki
  - utter_demanderCompteADebiter
* realiserVirement{"compteADebiter": "le compte de mon fils"}
  - slot{"compteADebiter": "le compte de mon fils"}
  - utter_merki
  - utter_demanderCompteACrediter
* realiserVirement{"compteACrediter": "le compte perso"}
  - slot{"compteACrediter": "le compte perso"}
  - utter_merki
  - utter_demanderConfirmationVirement
  - utter_confirmerOperationVirement
  - utter_autreAction
* aurevoir
  - utter_aurevoir
```

Then I train my model, and I have some strange behavior.
First if I ask to do a transfer (realiserVirement), it seems to work and the bot ask me for my transfer amount, once done it goes and asks me for the from where the transfer is done, but then, when I give the account (it's a text slot so I can give whatever I want, no verification), it's not responding anymore.

I then told me, maybe I uncorrectly created my story file, so I decide to go and try interactive learning, but each time I check the story I create during this exercise, it's exactly the same type of story than those I created myself.

And last point, if I don't put the bonjour and utter_bonjour in a single story, the bot is not likely to tell bonjour at the first launch when I tell him bonjour, why that?

If you need further files / details, don't hesitate, thank you.

**Comment by Frackup** [comment]
Hi, I keep on trying and find something that (I think) could help upgrade my dialog quality.
I'm using the bot.py file from the restaurant chatbot, and I adapted it. There I found that there's a parameter called max history, and hereunder is my bot.py (only the train_dialogue part):
```
def train_dialogue(domain_file="domain.yml",
                   model_path="models/dialogue",
                   training_data_file="data/dialog.md"):
    agent = Agent(domain_file,
                  policies=[MemoizationPolicy(), SGBotPolicy()])

    agent.train(
            training_data_file,
            max_history=5,
            epochs=400,
            batch_size=100,
            validation_split=0.2
    )

    agent.persist(model_path)
    return agent
```
I would like to understand this : what is the history underlined with the max_history variable. If I give a dialogue as the following, do I have 18 exchanges so I should put 18 in my variable? (which will make my training to last at least a year with my computer?) My tests seem to tell so:
```
## Dialog Virement sans informations 002
* bonjour
  - utter_bonjour
* realiserVirement{}
  - utter_demanderMontant
* realiserVirement{"montant": "1"}
  - slot{"montant": "1"}
  - utter_merki
  - utter_demanderCompteADebiter
* realiserVirement{"compteADebiter": "1"}
  - slot{"compteADebiter": "1"}
  - utter_merki
  - utter_demanderCompteACrediter
* realiserVirement{"compteACrediter": "2"}
  - slot{"compteACrediter": "2"}
  - utter_merki
  - utter_demanderConfirmationVirement
  - utter_confirmerOperationVirement
  - utter_autreAction
```

**Comment by tmbo** [comment]
@Frackup mind adding the domain file, the whole story file as well as the command you used for training? if there are any privacy concerns please feel free to send by mail. I'd like to completely reproduce this, so please let me know which kind of messages I need to send to the bot (intents are fine, no real messages. also dont need the nlu data, i dont think it is an nlu issue)

**Comment by Frackup** [comment]
Hi **tmbo**, Thanks for your reply. You'll find here all you asked for, hoping it will help to find out what's blocking me.

**Domain file:**
```
slots:
  montant:
    type: text
  compteACrediter:
    type: text
  compteADebiter:
    type: text
  compteAConsulter:
    type: text

entities:
- montant
- compteACrediter
- compteADebiter
- compteAConsulter

intents:
- bonjour
- aurevoir
- realiserVirement
- consulterSolde

actions:
- utter_bonjour
- utter_aurevoir
- utter_consulterSolde
- utter_merki
- utter_demanderConfirmationVirement
- utter_confirmerOperationVirement
- utter_demanderMontant
- utter_demanderCompteACrediter
- utter_demanderCompteADebiter
- utter_demanderCompteAConsulter
- utter_autreAction
- bot.ResetSlots

templates:
  utter_autreAction:
  - text: "Puis-je faire autre chose pour vous?"

  utter_bonjour:
  - text: "Bonjour, comment puis-je vous être utile?"

utter_consulterSolde:
  - text: "Voici le détail de votre compte bancaire."
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_merki:
  - text: "Je vous remercie."

  utter_demanderConfirmationVirement:
  - text: "Vous confirmez la demande de réalisation de virement depuis {compteADebiter} vers {compteACrediter} d'un montant de {montant} euros?"
    buttons:
    - title: "Je confirme"
      payload: "Je confirme"
    - title: "J'annule"
      payload: "J'annule"

  utter_confirmerOperationVirement:
  - text: "Je confirme que le virement d'un montant de {montant} € depuis {compteADebiter} vers {compteACrediter} a bien été réalisé."

  utter_demanderMontant:
  - text: "Pouvez-vous me préciser le montant du virement?"

  utter_demanderCompteACrediter:
  - text: "Vers quel compte souhaitez-vous effectuer le virement?"

  utter_demanderCompteADebiter:
  - text: "Depuis quel compte souhaitez-vous réaliser le virement?"

  utter_demanderCompteAConsulter:
  - text: "Quel compte souhaitez-vous consulter?"

  utter_aurevoir:
  - text: "Aurevoir."
```
For the whole story file, I added it since I created a .py file to generate automatically a dialog file (to have a large bunch of examples, almost 32K lines).
[stories.md.zip](https://github.com/RasaHQ/rasa_core/files/1810546/stories.md.zip)

And the command I used for NLU training is part of the bot.py file (present in the restaurant example provided by Rasa). I put you here the part of code (for the dialogue training, I put it in my initial post):
```
def train_nlu():
    from rasa_nlu.converters import load_data
    from rasa_nlu.config import RasaNLUConfig
    from rasa_nlu.model import Trainer

    training_data = load_data('data/train_file2.json')
    trainer = Trainer(RasaNLUConfig("config.json"))
    trainer.train(training_data)
    model_directory = trainer.persist('models/nlu/', fixed_model_name="current")

    return model_directory
```

Now regarding the fact to reproduce my issue, I use the following intents:
@realiserVirement
- The bot correctly ask for the "montant" slot (utter_demanderMontant)
@realiserVirement{"montant": "500"}
- The bot says utter_merki
- The bot asks for the compteADebiter slot (utter_compteADebiter)
@realiserVirement{"compteADebiter": "debit"}
- The bot says utter_merki
- The asks for the compteACrediter slot (utter_compteACrediter)
@realiserVirement{"compteACrediter": "credit"}
Then I have no answer from the bot, and if I hit enter many times, it goes again on utter_bonjour, but there's no consistency in the future dialogues I would have with it (the bot will directly says thank you (utter_merki) whatever I ask for, or even goodbye (utter_aurevoir)).
