### ISSUE TITLE
rasa_core model won't train when story starts with utterance

### ISSUE THREAD

**Issue by joseariel** [RasaHQ/rasa_core#300]
**Rasa Core version**:
0.7.9

**Python version**: 
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 

**Operating system** (windows, osx, ...):
Debian Jessie

**Issue**:
The rasa_core model won't train when the stories.md file has stories that are initiated by the bot, as opposed to the end-user. For instance, we're trying to train a model to start by asking 'How can we be of service?' and based on the response from the end-user take different subsequent actions (utterances).

Please see the following:

```yaml
## forgot_my_password_978as6df8a7df
    - utter_how_can_I_help
* _forgot_my_password
    - utter_application_assist

```

**Content of domain file** (if used & relevant):
```yaml
intents:
 - hello
 - forgot_my_password
 - thankyou

templates:
  utter_greet:
    - Hello!
  utter_how_can_I_help:
    - How can we be of service?
  utter_application_assist:
   - I'll be happy to assist you. Please visit http://... to reset your password.

actions:
  - utter_greet
  - utter_how_can_I_help
  - utter_application_assist

```
