### ISSUE TITLE
Trigger intent from inside a custom action 

### ISSUE THREAD

**Issue by aourednik** [RasaHQ/rasa_core#333]
**Rasa Core version**: 0.8.5

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 16

**Issue**: I am looking for a way to trigger an intent form inside a custom action, while handle_channel is running.

This seems necessary to handle a case in which a named entity, needed for further reactions from the bot, has not been correctly extracted: (```tracker.get_slot('person_name') is None```). 

I have tried this in the code below (run from command line with ``` python bot.py run```, only relavant part of code included). My attempt was to instantiate runagent Agent as a global variable, in order to be able to access the  ```handle_message``` method from within my custom class. This did not work. It is also probably not the best approach. Any help would be much appreciated.

```python

runagent = None # trying to set up running agent as a global variable

class ActionSearchPersonByName(Action):
    def name(self):
        return 'action_search_person_by_name'
    def run(self, dispatcher, tracker, domain):
        global runagent
        person_name = tracker.get_slot('person_name') 
        if person_name is not None :
            runagent.handle_message("/asks_for_person_search_with_provided_name")
            dispatcher.utter_message("Wait, I am looking for the person named " + person_name.title())
            return [SlotSet("found_records", "My API has found a record under this name")]
        else: 
            runagent.handle_message("/asks_for_person_search_without_providing_understandable_name")
            return [SlotSet("found_records", "I have found no records for your search")]

class ActionShowResult(Action):
    def name(self):
        return 'action_show_result'
    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message(tracker.get_slot('found_records'))
        return [SlotSet("person_name", None)]

...

def run(serve_forever=True):
    global runagent
    interpreter = RasaNLUInterpreter("models/nlu/default/current")
    runagent = Agent.load("models/dialogue", interpreter=interpreter)
    if serve_forever:
        runagent.handle_channel(ConsoleInputChannel())
    return runagent
```

## story example
...
* inform{"person_name": "dsga"}
  - action_search_person_by_name
* asks_for_person_search_without_providing_understandable_name
  - utter_i_did_not_understand_a_name
  - utter_tryagain
* affirm
  - prompt_person_search
* inform{"person_name": "Ich suche Herman Hesse"}
  - action_search_person_by_name
* asks_for_person_search_with_provided_name
  - action_show_result
  - utter_search_other_person
* deny
  - goodbye

**Content of domain file** (if used & relevant):
```yaml

...

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - search_person
  - inform
  - asks_for_person_search_with_provided_name
  - asks_for_person_search_without_providing_understandable_name

slots:
  person_name:
    type: text
  found_records:
    type: text

entities:
  - person_name

...

```
