### ISSUE TITLE
buttons- where to put the quotation marks?

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#365]
hi,

I struggle how to format buttons with intents and entities for slack.

```yaml
utter_bla
    - text: "balaba"
      buttons:
         - title: "yes"
           payload: "/affirm{entity: value}"
         - title: "No"
           payload: "/deny{entity: value}"

```
When I use this slack cannot parse the payload. It wants quotation marks. But if I do them there is an error with the domain.yml because of the quotation marks??!!

```yaml
utter_bla
    - text: "balaba"
      buttons:
         - title: "yes"
           payload: "/affirm{"entity":" value"}"
         - title: "No"
           payload: "/deny{"entity": "value"}"

```

Where doo you have to set the quotation marks?

**Comment by ctrado18** [comment]
@tmbo some time ago you poset on gitter a statement to this but with the format like in the last one where evrything are quotation marks. But this yields errors for the yml format? The solution should be simple, right?

**Comment by tmbo** [comment]
It should be possible to use single quotes, e.g.:

```
utter_bla
    - text: "balaba"
      buttons:
         - title: 'yes'
           payload: '/affirm{"entity":" value"}'
         - title: 'No'
           payload: '/deny{"entity": "value"}'
```
