### ISSUE TITLE
Custom Actions not working with Action Factory: Remote

### ISSUE THREAD

**Issue by Nectarineimp** [RasaHQ/rasa_core#366]
**Rasa Core version**: rasa-core (0.8.5), rasa-nlu (0.11.4)

**Python version**: Python 3.6.3 :: Anaconda custom (64-bit)

**Operating system** (windows, osx, ...): Windows 10 Pro 64 AND Docker/Linux

**Issue**: If "action factory: remote" is set in the domain file, using a custom action's name will cause training the core to fail. Replacing the name with the module.class of the action will work, however. When the action is called with curl or other methods, no error is given, but the action does not execute.

**Content of domain file** (if used & relevant):
```
actions:
  - Scenario_Pricing_Actions.ActionCheckOwnershipType
  - run_retail_scenario

intents:
  - retail_scenario

entities:
  - property_value
  - down_payment
  - fico
  - ownership_type
  - normalize_ownership

slots:
  down_payment:
    type: text
  fico:
    type: text
  ownership_type:
    type: text
  property_value:
    type: text
  normalized_ownership:
    type: unfeaturized

templates:
  utter_default:
  - text: "Input not understood."
  run_retail_scenario:
  - text: "Data: {ownership_type}, {normalized_ownership}, {property_value}, {down_payment}, {fico}"

action_factory: remote
```
