### ISSUE TITLE
action_restart does not trigger

### ISSUE THREAD

**Issue by ewagner70** [RasaHQ/rasa_core#470]
**Rasa Core version**: 0.9.0a5

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: after upgrading to 0.9.0a5, action_restart does not trigger anymore 
```
from rasa_core.actions import Action
from rasa_core.actions.action import ActionRestart
from rasa_core.actions.forms import FormAction
from rasa_core.actions.forms import EntityFormField, BooleanFormField
from rasa_core.events import SlotSet

class UtterDefault(Action):
    def name(self):
        return "utter_default"
    def run(self, dispatcher, tracker, domain):
        latest_message = tracker.current_state()['latest_message']
        usr_input = latest_message['text']
        dispatcher.utter_message(output_result(usr_input))
        return[]

class ActionReportCoI(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("coi_type", "coi_type"),
            EntityFormField("PERSON", "coi_gi_counterpartyname"),
            EntityFormField("coi_gi_is_po", "coi_gi_is_po"),
            EntityFormField("coi_gi_give_or_take", "coi_gi_give_or_take"),
            EntityFormField("coi_amount", "coi_amount")
        ]

    def name(self):
        return 'action_report_coi'

    def submit(self, dispatcher, tracker, domain):
        results = tracker.get_slot("coi_gi_counterpartyname") + \
                  str(tracker.get_slot("coi_amount"))
                  #tracker.get_slot("coi_gi_is_po")
                  #str(tracker.get_slot("coi_gi_give_or_take"))
        print("ALL RESULTS:", tracker.get_slot("coi_gi_counterpartyname"), tracker.get_slot("coi_amount"), tracker.get_slot("coi_gi_is_po"), tracker.get_slot("coi_gi_give_or_take"))
        #SlotSet("search_results", results)
        ActionRestart()
        return []
```

**Content of domain file** (if used & relevant):
```yaml
## report_coi_invitation_false_give
* reportcoi
  - action_report_coi
  - slot{"requested_slot": "coi_type"}
* reportcoi{"coi_type": "gifts_invitations"}
  - action_report_coi
  - slot{"coi_type":"gifts_invitations"}
  - slot{"requested_slot": "coi_gi_give_or_take"}
* reportcoi{"coi_gi_give_or_take": "give"}
  - action_report_coi
  - slot{"coi_gi_give_or_take": "give"}  
  - slot{"requested_slot": "coi_gi_counterpartyname"}
* coi_gi_counterpartyname{"coi_gi_counterpartyname": "coi_gi_counterpartyname"}
  - action_report_coi
  - slot{"coi_gi_counterpartyname": "eric wagner"}
  - slot{"requested_slot": "coi_gi_is_po"}
* coi_gi_is_po{"coi_gi_is_po": "is_not_public"}
  - action_report_coi
  - slot{"coi_gi_is_po": "is_not_public"}
  - slot{"requested_slot": "coi_amount"}
* coi_amount{"coi_amount": "1000"}
  - action_report_coi
  - slot{"coi_amount": "1000"}
  - action_restart

## report_coi_invitation_false_receive
* reportcoi
  - action_report_coi
  - slot{"requested_slot": "coi_type"}
* reportcoi{"coi_type": "gifts_invitations"}
  - action_report_coi
  - slot{"coi_type":"gifts_invitations"}
  - slot{"requested_slot": "coi_gi_give_or_take"}
* reportcoi{"coi_gi_give_or_take": "receive"}
  - action_report_coi
  - slot{"coi_gi_give_or_take": "receive"}  
  - slot{"requested_slot": "coi_gi_givername"}
* coi_gi_counterpartyname{"coi_gi_counterpartyname": "coi_gi_counterpartyname"}
  - action_report_coi
  - slot{"coi_gi_counterpartyname": "eric wagner"}
  - slot{"requested_slot": "coi_gi_is_po"}
* coi_gi_is_po{"coi_gi_is_po": "is_not_public"}
  - action_report_coi
  - slot{"coi_gi_is_po": "is_not_public"}
  - slot{"requested_slot": "coi_amount"}
* coi_amount{"coi_amount": "1000"}
  - action_report_coi
  - slot{"coi_amount": "1000"}
  - action_restart


intents:
 - greet
 - default
 - goodbye
 ...
 - action_restart

actions:
  - utter_greet
  - utter_goodbye
  - utter_thankyou
  - utter_reportcoi
  - utter_username
  - utter_reported_for_name
  - utter_ask_coi_type
  - utter_ask_coi_gi_counterpartyname
  - utter_ask_coi_gi_give_or_take
  - utter_ask_coi_gi_is_po
  - utter_ask_coi_share
  - utter_ask_coi_amount
  - utter_ask_coi_remarks
  - utter_ask_coi_sa_company
  - utter_ask_coi_sa_hours_per_week
  - georgebot.ActionReportCoI
  - georgebot.SetUsername
  - georgebot.SetReportedforname
  - georgebot.UtterDefault
  - utter_restart

templates:
  utter_greet:
    - "hey there {username}!"    # variable will be filled by slot with the same name or by custom code
  ...
  utter_restart:
    - "Restarted Action!"
```
