### ISSUE TITLE
Is there any limit to number of buttons in slack integrator of rasa core?

### ISSUE THREAD

**Issue by amirkhn33** [RasaHQ/rasa_core#481]
**Rasa Core version**: 0.8.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: I am trying to display 6 buttons in Slack but none of them gets displayed. Whereas five of them work fine together.
Also, if I want to display a mesage which starts on a new line in a single utterance then how can I insert a newline in a single utterance?

**Content of domain file** (if used & relevant):
```yaml
buttons:
     -  title: "Q1"
        payload: "Question 1"
     -  title: "Q2"
        payload: "Question 2"
     -  title: "Q3"
        payload: "Question 3"
     -  title: "Q4"
        payload: "Question 4"
     -  title: "Q5"
        payload: "Question 5"
     -  title: "Q6"
        payload: "Question 6"
```
