### ISSUE TITLE
How to put the slots as mandatory.

### ISSUE THREAD

**Issue by DhruvMevada** [RasaHQ/rasa_core#506]
**Rasa Core version**: 0.9.0a5
**Issue**:  
Example: " I want to book a movie ticket."

Then Bot should ask to user that please provide the time & locations. Until the slots :- locations & time is not fill the Bot will repeat the question.

**Comment by auzair92** [comment]
You can use Rasa's `FormAction` class to achieve this. Forms make it easier to define required fields and it handles most of the stuff for you. Relevant documentation with examples can be found [here](https://core.rasa.com/master/patterns.html).

**Comment by DhruvMevada** [comment]
Ya, I have tried that, but still not getting that. Please help me if  I'm doing any mistake here.
**Yaml file**
```yaml
intents:
  - greetings
  - booking
  - confirm
  - goodbye

entities:
- city
- destination_location
- source_location

slots:
  city:
    type: text
  source_location:
    type: text
  destination_location:
    type: text
  requested_slot:
    type: unfeaturized


templates:
  act_greet:
    - "Hi there!!"
    - "Greetings for the day"
    - "Hello, Have a good day"
    - "How can I help you"

  act_booking:
    - "booking a ride"
  act_confirm:
    - "Your travelling from {source_location}, {city} to {destination_location}, {city} on {travel_date} {travel_time} 
    Are you want to Book this ?"
  act_goodbye:
    - "Good Bye"
  act_cancel:
    - "you have cancel your booking!!"
  utter_ask_source_location:
    - "Please provide me source location"
  utter_ask_destination_location:
    - "please provide me destination location"
  utter_ask_city:
    - "in which city you currently living"

actions:
- act_greet
- act_confirm
- act_booking
- act_goodbye
- act_cancel
- actions.ActionBooking
#- bot.ActionSuggest
```

**Stories.md file**
```yaml

## story_1
* greet
 - act_greet
* booking
 - action_booking
 - slot{"requested_slot": "source_location"}
 - slot{"requested_slot": "destination_location"}
 - slot{"requested_slot": "city"}
 
* bye
 - act_goodbye
```
**custom action class of actions.py file**
```yaml
class RestaurantAPI(object):
   def search(self, info):
       return "papi’s pizza place"

class ActionBooking(FormAction):

   RANDOMIZE = False

   @staticmethod
   def required_fields():
       return [
           FreeTextFormField("destination_location", "destination_location"),
           FreeTextFormField("source_location", "source_location"),
           FreeTextFormField("city", "city")
       ]

   def name(self):
       return "action_booking"

   def run(self, dispatcher, tracker, domain):
       dispatcher.utter_message("looking for restaurants")
       restaurant_api = RestaurantAPI()
       restaurants = restaurant_api.search(tracker.get_slot("city"))
       return 

```


**output with debug command, Here the slots source & destination locations are filled, but the bot not asked regarding missing slot city.**

![image](https://user-images.githubusercontent.com/9553239/40365036-533c6518-5df1-11e8-8031-e15568320ffc.png)
