### ISSUE TITLE
WARNING:rasa_core.processor:Circuit breaker tripped. Stopped predicting more actions for sender 'default'

### ISSUE THREAD

**Issue by hardiksanchawat** [RasaHQ/rasa_core#521]
**Rasa Core version** 0.8.6

**Python version** 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:  WARNING:rasa_core.processor:Circuit breaker tripped. Stopped predicting more actions for sender 'default'

While getting a response from a bot, same response displayed multiple times and getting WARNING:rasa_core.processor: Circuit breaker tripped. Stopped predicting more actions for sender 'default'.

Anyone could explain how to fix this issue?

Regards

**Comment by tmbo** [comment]
Which action is predicted multiple times?

**Comment by hardiksanchawat** [comment]
![response_come_multiple_time](https://user-images.githubusercontent.com/7599315/40422427-ebc9592e-5eac-11e8-9c1e-9c76441a4dc3.PNG)

As you can see in the attachement for one of the query it is giving the repeated response and this occurs randomly for some questions. Sometimes  the bot will respond normally for all the queries but will give repeated resonses. And the warning I am getting is ```WARNING:rasa_core.processor: Circuit breaker tripped. Stopped predicting more actions for sender 'default'```

FYI: Also we are running locally.

Kindly find the attachment.

Thanks

**Comment by akelad** [comment]
Can you post your stories file?

**Comment by hardiksanchawat** [comment]
@akelad I'm using rasa-core: **0.8.6** 
Below content belongs to my stories.md
```
## first story
* greet
    - utter_greet

## third story
* OverallSpend
	- overall_spend

## fourth story
* DisocuntCapturePercentage
	- discoount_capture_percentage

## fifth story
* dpo
    - action_askingDpo

## sixth story
* dpo_compare
	- action_comparingDpo

## seventh story
* dpo_vendor
    - action_askingVendor

## eight story
* trend
    - action_askingTrend

## ninth story
* overall_spend_rise
    - action_askingOverall

## ten story
* overall_spend
    - action_spend

## elevanth story	
* overall_spend_payterm
    - payterm_spend
```

**Comment by akelad** [comment]
and your domain file?

**Comment by hardiksanchawat** [comment]
@akelad Below code belongs to my domain.yml

```
intents:
    - greet
    - OverallSpend
    - DisocuntCapturePercentage
    - dpo
    - dpo_compare
    - dpo_vendor
    - trend
    - overall_spend_rise
    - overall_spend
    - overall_spend_payterm
    - PayTermsVendorCompare
    
entities:
    - year
    - payterm
    - measure
    - month
    - vendor
    - discount
 
slots:
    year:
        type: text
    measure:
        type: text
    payterm:
        type: text
    month:
        type: text
    vendor:
        type: text
    discount:
        type: text

templates:
    utter_greet:
        - 'Hello, how can I help you?'
        - 'Hi, I am here to help.'
        
actions:
    - utter_greet
    - actions.OverallSpend
    - actions.DisocuntCapturePercentage
    - actions.AskDpo  
    - actions.Comparision
    - actions.Vendors
    - actions.AskTrend
    - actions.Overall
    - actions.OverallSpend1
    - actions.PayTerms
    - actions.PayTermsVendorCompare
```
