### ISSUE TITLE
 classifying multiple intents

### ISSUE THREAD

**Issue by MinhMinnie** [RasaHQ/rasa_core#570]
**Rasa Core version**:0.9.0

**Python version**: 3.6.5

**Operating system** (windows, osx, ...):OSX 10.11.6

**Issue**:multiple intents in a sentence

Hello, 
Does Rasa NLU support a classifier for classifying multiple intents in the same sentence ? I've trained Rasa NLU model using tensorflow_embedding pipeline as I've read the article "Supervised Word Vectors from Scratch in Rasa NLU" but it doesn't work.

**Comment by MinhMinnie** [comment]
Please help me

**Comment by Ghostvv** [comment]
@MinhMinnie could you please provide more details

**Comment by amn41** [comment]
Hi @MinhMinnie - I guess your question is about Rasa Core (you ask about Rasa NLU). If you have sentences where multiple intents are predicted, you can also write stories for them, e.g.:

```
## story
* intent1+intent2
   - action_1
```

**Comment by MinhMinnie** [comment]
@Ghostvv  @amn41  For instance, the sentence: " Hello. I am looking for a Mexican restaurant in the center" has 2 intents : greet and search_restaurant. How can I capture this in Rasa NLU?

**Comment by amn41** [comment]
ok got it. you need to add some examples like this to your training data:

```
#intent:greet+search_restaurant
-  Hello. I am looking for a Mexican restaurant in the center
...

#intent:greet
- hello
...
```

and then the corresponding config:

```
language: "en"

pipeline:
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```

though this is really a question for the Rasa NLU repo

**Comment by MinhMinnie** [comment]
@amn41  I follow your instruction but it gives me:
confidence for search_restaurant : 0.9097
confidence for greet+search_restaurant : 0.0587

**Comment by MinhMinnie** [comment]
my training_data:
{
   "text" : "Hello.  I am looking for a Mexican restaurant in the center",
   "intent": "greet+ search_restaurant",
   "entites": [
   {
      "start":
      "end":
      "value":
      "entity":
   },
   {
      "start":
      "end":
      "value":
      "entity":
   }
  ]
}

**Comment by amn41** [comment]
How many examples did you add? if you only add one I wouldn't expect very good performance, because there are so many examples of other intents. you should try to balance the classes a bit

**Comment by MinhMinnie** [comment]
@amn41 Yes, you are right. But There isn't  any entity displayed when I run the server : 
python -m rasa_nlu.server --path projects
curl -X POST localhost:5000/parse -d '{"q":"..."}'
It gives me an empty entity

**Comment by akelad** [comment]
ah to use entity extraction with tensorflow, you need to add a few things:
```
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"
```
