### ISSUE TITLE
setting slots directly from buttons

### ISSUE THREAD

**Issue by disimone** [RasaHQ/rasa_core#583]
**Rasa Core version**:
commit b0b76d8076b7165345477715b886f5771081c7f5

**Python version**: 
3.5.2

**Operating system** (windows, osx, ...):
linux
**Issue**:

Hi, in the docs, you say that in case of a purely button-based bot, we would not need an NLU interpreter at all. However, I could not find the instructions on how to set slots directly from the buttons.

Examples and discussions I have found here seem to proceed as follows:

- define a button with a payload
- train an nlu interpteter to properly understand the payload and set the intent/entities
- let rasa_core map entities to slots

In a purely button-based bot, however, I think the best thing would be to let the button directly set intent and entities/slots. Is this supported? How does one avoid the NLU altogether?

Thanks for your help,

Andrea.

**Comment by disimone** [comment]
I tried to use explicit intent/entity setting in the payload, like in

```
  utter_q1:
    - text: "test question 1"
      buttons:
      - title: "answer 1.1"
        payload: "/intent_1{\"test_slot_1\":\"test_value_1\"}"
      - title: "answer 1.2"
        payload: "/intent_1{\"test_slot_1\":\"test_value_2\"}"
```
but this does not appear to work. apparently the user input "1" from the console is parsed as "1", not as the payload.
