### ISSUE TITLE
How to use the /respond endpoint and custom actions?

### ISSUE THREAD

**Issue by GabrielGuimbaud** [RasaHQ/rasa_core#588]
Hello,

I am trying to use the new /respond endpoint with rasa_core, and it doesn't work when I'm activating the remote mode in domain.yml ( `action_factory: remote` ) : it is just responding empty array : `[]`

The thing is I need the bot to do some custom scripted actions that are not simple utterances (and are located in another file here called actions.py). For this purpose I dont know any other way than using the remote mode.
Is there any way to solve my problem ? Such as a way to create custom actions without using the remote mode ? Or should I just just wait for a new update to handle remote mode and /respond endpoint ?

Thanks

**Rasa Core version**: 0.9.3

**Python version**: Python 3.6.5

**Operating system**: Linux

**Issue**: Unable to use the /respond endpoint and custom actions

**Content of domain file**:
```yaml
intents:
  - get_definition
  - greet

entities:
  - word

actions:
  - utter_greet
  - actions.actiongetdefinition
  
templates:
  utter_greet:
    -  "Hi"

action_factory: remote
```
