### ISSUE TITLE
MoodBot does not respond to my slack messages

### ISSUE THREAD

**Issue by marchnair** [RasaHQ/rasa_core#613]
**Rasa Core version**: '0.8.2'

**Python version**: 3.6

**Operating system** (windows, osx, ...):windows 10

**Issue**:
I installed the starter-pack and followed the instructions here:
https://core.rasa.com/tutorial_basics.html#tutorial-basics
to set up the rasa moodbot

I also configured slack using the ngrok https webhook.

I am not getting any response from the moodbot in slack.

So I test this:
curl -XGET 127.0.0.1:5002/webhook -d '{"text":"bye"}'
This is also not giving me any response from the mood bot. However, I see 
127.0.0.1 - - [2018-06-12 22:10:17] "GET /webhook HTTP/1.1" 200 115 0.001003 
where I run the command:
python -m rasa_core.run -d models/current/dialogue -u models/current/nlu --port 5002 --connector slack --credentials slack_credentials.yml

I also tried:
curl -XPOST http://b928f88d.ngrok.io/webhook -d '{"text":"bye"}'
I don't see anything happening at my server end.

How do I get my moodbot to respond to "hi" or "bye" from slack??

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - goodbye
  - mood_affirm
  - mood_deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great"
      payload: "great"
    - title: "super sad"
      payload: "super sad"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"
```
