### ISSUE TITLE
Problem with intent repeats and not predict right next action

### ISSUE THREAD

**Issue by reza-ebrahimi** [RasaHQ/rasa_core#663]
**Rasa Core version**: master branch

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Environment**: https://github.com/reza-ebrahimi/rasa_venv

**Issue**:
intents repeats with jumping over them and executing their actions continuously. it is also doesn't predict right next intent.

**Content of domain file** (if used & relevant):
```yaml
language: "en"
pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_split_symbol: "_"
```
