### ISSUE TITLE
slots filling question

### ISSUE THREAD

**Issue by e8180kimo** [RasaHQ/rasa_core#678]
**Rasa Core version**: 0.9.6

**Python version**: 3.6

**Operating system** (windows, osx, ...): win10

**Issue**: I have a problem with filling the slots and call it back. I want the bot reply the "essay_topic" after the user types an essay topic, such as motivation. But after I type "motivation", the bot replied "so your topic is None"

**Content of domain file** (if used & relevant):
```yaml
intents:
  - greet
  - good_bye
  - request
  - choose_topic_yes_confirm
  - deny_topic
  - essay_topic
  - choose_type_of_paper

actions:
- utter_greet
- utter_what_topic
- utter_essay_topic
- actions.ActionTopic

entities:
  - essay_topic

slots:
  essay_topic:
    type: text
  requested_slot:
    type: unfeaturized  
    
templates:
  utter_greet:
  - text: "How may I help you?"
       
  utter_what_topic:
  - text: "What is your topic?"
  
  utter_essay_topic:
  - text: "so your topic is {essay_topic}"
  
```

Story.md
```
## writing path 1<!-- name of the story - just for debugging -->
* greet
  - utter_greet <!-- action of the bot to execute -->
* request
  - utter_what_topic
* essay_topic
  - utter_essay_topic
  - slot{"requested_slot": "essay_topic"}
```

actions.py
```
class ActionTopic(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("essay_topic", "essay_topic"),
            
        ]
    def name(self):
        return 'action_topic'

    def run(self, dispatcher, tracker, domain):
        essay_topic = tracker.get_slot("essay_topic")
        dispatcher.utter_message(essay_topic)
        return []
```
