### ISSUE TITLE
Getting pykwalify.errors.CoreError: <CoreError: error code 3: Unable to load any data from source yaml file: Path: '/' error when trying to add buttons to my bot.

### ISSUE THREAD

**Issue by devansh1497** [RasaHQ/rasa_core#694]
**Rasa Core version**:0.8.0

**Python version**: 3.6.4

**Operating system** (windows, osx, ...):OSX

**Issue**:So, I am trying to add some buttons to my chatbot but whenever I add them as shown in the example, I get the above mentioned error meaning that somehow my domain.yml file becomes invalid.
Can someone please help me on this?Also, I couldn't find anywhere what the 'payload' in these button means...Can you help me on this as well?

**Content of domain file** (if used & relevant):
```yaml
slots:
  all_issues:
    type: text
    initial_value: None
  bugs:
    type: text
    initial_value: None
  stories:
    type: text
    initial_value: None
  project_name:
    type: text
  med_pri:
    type: text
  low_pri: 
    type: text
  high_pri:
    type: text
  
intents:
 - greet
 - goodbye
 - inform
 - anything_else

entities:
 - all_issues
 - bugs
 - stories
 - project_name
 - low_pri
 - med_pri
 - high_pri

templates:
  utter_greet:
    - 'Hello!How can I help?'
    - 'Hi!'
  utter_goodbye:
    - 'Talk to you later.'
    - 'Bye!'
  utter_anything_else:
    - "Can I help you with anything else?"
    - "Anything else?"
    - "Do you need anything else?"
    
  utter_ask_project_name:
    - text: "Which project?"
    buttons:
    - title: "FAE"
      payload: "FAE"
    - title: "TPO"
      payload: "CDF"

  utter_ask_default:
    - "Sorry.I don't understand."

actions:
 - utter_greet
 - utter_goodbye
 - utter_anything_else
 - utter_ask_project_name
 - utter_ask_default
 - actions.ActionIssue 


```
