### ISSUE TITLE
Can Rasa handle question answering

### ISSUE THREAD

**Issue by arachny** [RasaHQ/rasa_core#716]
**Rasa Core version**: 0.9.7

**Python version**:  3.6

**Operating system** (windows, osx, ...): ubuntu18.04

**Issue**:

I just wanted to have your opinion on whether Rasa can handle multiple questions and answers that normally would not be more than just one level or two of a dialogue flow. For example asking several websites offer Q&As that could potentially be handled by the chatbot.

I can see how Rasa's intent recognition would work nicely and find what the question is about, but then how would it pick from an answer, especially if there are multiple matches.

I suppose we could build many intents that map to a few answers (to randomly select from), but what if there are thousands of intents (i.e. questions) and those keep growing. Can Rasa handle anything like that (since is already using SpaCy for featurisation) or should we be looking to integrate Rasa into another modules?

Anyone has any experiences or ideas?

**Comment by akelad** [comment]
Sure, QA is possible by providing short stories. I would imagine that these thousands of questions would probably fall into a few more general intents, in which case NLU should be able to handle this.
Have you tried out the tensorflow_embedding pipeline yet? In our experience this works better for things like faq intents

**Comment by arachny** [comment]
Ok, that is interesting! So lets try to build an example if you dont mind. Say we wanted to build a chatbot to help potential users understand the Rasa offering and how it compares against other similar chatbots. So the chatbot would need to answer the following questions (sample):

- Q1: Why python?
- A1: Because of its ecosystem of machine learning tools. Head over to But I don’t code in python! for details.

- Q2: Is this only for ML experts?
- A2: You can use Rasa if you don’t know anything about machine learning, but if you do it’s easy to experiment.

- Q3: How much training data do I need?
- A3: You can bootstrap from zero training data by using interactive learning. Try the tutorials!

- Q4: How is Rasa different from other approaches?
- A4: Rather than writing a bunch of if/else statements, a Rasa bot learns from real conversations. A probabilistic model chooses which action to take, and this can be trained using supervised, reinforcement, or interactive learning.

- Q5: Where to Start
- A5: After going through the Installation, most users should start with Building a Simple Bot. However, if you already have a bunch of conversations you’d like to use as a training set, check the Supervised Learning Tutorial.

- Q6: What is Rasa NLU
- A6: You can think of Rasa NLU as a set of high level APIs for building your own language parser using existing NLP and ML libraries. The setup process is designed to be as simple as possible.

- Q7: What is Rasa Core
- A7: Rasa Core takes in structured input: intents and entities, button clicks, etc., and decides which action your bot should run next. If you want your system to handle free text, you need to also use Rasa NLU or another NLU tool.


So the intents would be something like:
```
intents:
 - rasa_whatis
 - rasa_technical
 - rasa_comparison
 - ... (other intents like greet, etc.)
```

The NLU intent examples would be:
```
## intent : rasa_whatis
 - What is Rasa NLU
 - What is Rasa Core

## intent : rasa_technical
 - Why python?
 - Is this only for ML experts?
 - How much training data do I need?
 - Where to Start

## intent : rasa_comparison
 - How is Rasa different from other approaches?
```

And the utters would be:
```
utter_technical_A1:
  - text: "Because of its ecosystem of machine learning tools. Head over to But I don’t code in python! for details."
utter_technical_A2:
  - text: "You can use Rasa if you don’t know anything about machine learning, but if you do it’s easy to experiment."
utter_technical_A3:
  - text: "You can bootstrap from zero training data by using interactive learning. Try the tutorials!"
utter_comparison_A4:
  - text: "Rather than writing a bunch of if/else statements, a Rasa bot learns from real conversations. A probabilistic model chooses which action to take, and this can be trained using supervised, reinforcement, or interactive learning."
utter_technical_A5:
  - text: "After going through the Installation, most users should start with Building a Simple Bot. However, if you already have a bunch of conversations you’d like to use as a training set, check the Supervised Learning Tutorial."
utter_whatis_A6:
  - text: "You can think of Rasa NLU as a set of high level APIs for building your own language parser using existing NLP and ML libraries. The setup process is designed to be as simple as possible."
utter_whatis_A7:
  - text: "Rasa Core takes in structured input: intents and entities, button clicks, etc., and decides which action your bot should run next. If you want your system to handle free text, you need to also use Rasa NLU or another NLU tool."
```


Is that right? But again... I am not sure how I would build the stories. For example would it be like:
```
## example 1
* rasa_technical
 - utter_technical_A1

## example 2
* rasa_technical
 - utter_technical_A2
```

But then how does one get correctly chosen when there are two equal options in the story? My only guess would be to extract some entities and use those as examples (e.g. `rasa_technical{"technology": "python"}`)? But that would mean that we need to model each intent to extract entities from them... unless there is a way to use the entire user input (sentence) in the same way as the entities?

Could you possibly share your thoughts or provide a few example stories for the above Q&As?
