### ISSUE TITLE
Example of Button triggering custom action needed

### ISSUE THREAD

**Issue by arcontechnologies** [RasaHQ/rasa_core#721]
**Rasa Core version**:
0.9.7
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
A clear and precise example for using a button to trigger custom action. A professional grade example will be appreciable. nothing in documentation is referring to this.

What are the limitations for using buttons (from dialogue flow perspective).

**Comment by akelad** [comment]
You can set the payload of a button to be a specific intent (also including an entity if you want) and then add this to your stories, e.g.:

Add this to your domain file
```
  utter_ask:
  - text: "Do you want to continue the conversation?"
    buttons:
    - title: "Yes"
      payload: "/mood_affirm"
    - title: "No"
      payload: "/mood_deny"
```
and then add this to your stories file:
```
# story 1
* some_user_intent
  - utter_ask
* mood_affirm
  - do_something

# story 2
* some_user_intent
  - utter_ask
* mood_deny
  - do_something_else
```

The benefit of this is that if the user clicks the button, there's no risk of intent misclassification from NLU or anything. But you need to be aware that unless the text field is no longer present, the user can still enter any text and so you also need NLU training data for this
