### ISSUE TITLE
Form action asks twice the same question

### ISSUE THREAD

**Issue by MatheusFaria** [RasaHQ/rasa_core#755]
**Rasa Core version**: master@7ca2a23
**Rasa NLU version**: master@7a37ff8

**Python version**:  Python 3.6.4

**Operating system** (windows, osx, ...): Debian 9

**Issue**: When using Form Action the bot always asks the last question twice before submitting the form. As shown in the dialog below:

```
[rasa] Bot loaded. Type a message and press enter: 
[user] Hi

[rasa] Hey =)
[rasa] What is your Car Model?
[user] I have a corolla

[rasa] What is your zipcode?
[user] My zipcode is 12345

[rasa] Do you have driver's license?
[user] Yes

[rasa] Thank you! Bye...
[user] bye

[rasa] car_model_slot: corolla
[rasa] has_driver_license_slot: None
[rasa] requested_slot: has_driver_license_slot
[rasa] zipcode_slot: My zipcode is 12345
[rasa] Bye o/

[user] Hi
[rasa] Hey =)

[rasa] Do you have driver's license?
[user] yes

[rasa] Submitting Form...
[api-call] car_model: corolla has_driver_license: True zipcode: My zipcode is 12345
```

Here is the `domain` and my custom action file:

```yaml
intents:
  - greet
  - affirm
  - deny
  - inform_car_model
  - inform_zipcode
  - bye

entities:
  - car_model

slots:
  requested_slot:
    type: unfeaturized
  car_model_slot:
    type: text
  has_driver_license_slot:
    type: bool
  zipcode_slot:
    type: text

templates:
  utter_greet:
    - "Hey =)"
  utter_ask_car_model_slot:
    - "What is your Car Model?"
  utter_ask_has_driver_license_slot:
    - "Do you have driver's license?"
  utter_ask_zipcode_slot:
    - "What is your zipcode?"
  utter_bye:
    - "Bye o/"
  utter_useful:
    - "Was this information useful?"
  utter_thanks:
    - "Thank you! Bye..."

actions:
  - utter_greet
  - utter_ask_car_model_slot
  - utter_ask_has_driver_license_slot
  - utter_ask_zipcode_slot
  - utter_bye
  - utter_useful
  - utter_thanks
  - bot.actions.ActionDriverLicenseForm
  - bot.actions.ActionListSlots
```

```python
from rasa_core.actions.action import Action
from rasa_core.actions.forms import FormAction, EntityFormField, BooleanFormField, FreeTextFormField
from rasa_core.events import SlotSet

class ActionListSlots(Action):
    def name(self):
        return 'action_list_slots'

    def run(self, dispatcher, tracker, domain):
        for key in tracker.slots:
            dispatcher.utter_message(
                "{}: {}".format(key, tracker.slots[key].value)
            )
        return []

class ActionDriverLicenseForm(FormAction):

    RANDOMIZE = False

    @staticmethod
    def required_fields():
        return [
            EntityFormField("car_model", "car_model_slot"),
            FreeTextFormField("zipcode_slot"),
            BooleanFormField("has_driver_license_slot", "affirm", "deny"),
        ]

    def name(self):
        return 'action_driver_license_form'

    def submit(self, dispatcher, tracker, domain):
        dispatcher.utter_message('Submitting Form...')
        dispatcher.utter_message(
            'car_model: {} has_driver_license: {} zipcode: {}'.format(
                tracker.get_slot("car_model_slot"),
                tracker.get_slot("has_driver_license_slot"),
                tracker.get_slot("zipcode_slot"),
            )
        )

        return []
```
You can check the whole bot [here](https://github.com/MatheusFaria/rasa-bot-example/tree/5c016aebf2a4f1967230cb8f3a9f1137cec117bc) with the `Dockerfile` to run the bot in the console.
