### ISSUE TITLE
Slot names with german Umlauts

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#938]
Hi,

I found that umlaute are not set properly (in this for slots but maybe also for other things like entities?)

`WARNING:rasa_core.slots:Categorical slot 'slot1' is set to a value ('Ã¤pfel) that is not specified in the domain. `

Rasa Core version: 10.4

Python version: 3.6

Content of domain file (if used & relevant):
Example:

```
obst:
    type: categorical
    values: 
    - Äpfel
    - Birne

```
I don't have this as an entity if this might the issue?
