### ISSUE TITLE
Slot variable in payload of button

### ISSUE THREAD

**Issue by ctrado18** [RasaHQ/rasa_core#990]
Hey,

this here http://rasa.com/docs/core/0.10.4/domains/#variables is not working when you have the varibale inside payload title of button. Is this correct? Would be nice if so...

Core 10.4

**Comment by akelad** [comment]
what do you mean? Can you post an example of what you're trying to do?

**Comment by ctrado18** [comment]
Just giving variable in payload or title of button, both don't work:

```
 utter_greet:
  - text: "Hey! How are you?"
    buttons:
    - title: "great {name}"
      payload: "{name}great"
    - title: "super sad"
      payload: "super sad"

```

This would be nice because then you can more easily send payload buttons with variable intent and entities!
